#!/bin/bash
# ON YEKT-BILLING/DB
vim /etc/rsyslog.conf |
| *.* @192.168.2.200
systemctl restart rsyslog
logger -p err PRIVET
# ON SERVER YEKT-WORKER
vim /etc/rsyslog.conf |
| # Uncomment UDP block on MODULES
| module(load="immark")
| -
| module(load="imudp")
| input(type="imudp" port="514")

Проверяем права
$FileCreateMode 0644
$DirCreateMode 0755
$Umask 0022

| # GLOBAL DIRECTIVES
| if $hostname contains 'YEKT-DB' or $fromhost-ip contains "192.168.2.150" then {
|    *.* /home/yekt_admin/Desktop/Logs/YEKT-DB.log
| }
| if $hostname contains 'YEKT-BILLING' or $fromhost-ip contains "192.168.2.100" then {
|    *.* /home/yekt_admin/Desktop/Logs/YEKT-BILLING.log
| } 

//На всякий случай создаем эту папку (Если каталог не создался) и пользователя 
adduser yekt_admin
mkdir /home/yekt_admin/Desktop/Logs/
