#!/bin/bash
apt update
apt install libpam-modules
vim etc/X11/fly-dm/fly-dmrc | ShowBoxMEssage = true
vim /etc/pam.d/common-auth |
| account required pam_time.so
| account [success=1 default=ignore] pam_succeed_if.so user ingroup administrator
| account required pam_echo.so "Доступ запрещен! В случае необходимости доступа к рабочему месту вне регламентированных работ, напишите на почту admin@company.cool"
vim /etc/security/time.conf |
| *;*;!administrator|!root;Al0900-1800

# GROUP AUTH ON PASSWD| ON MSK-ADMINPC
vim /etc/login.group.allow |
| it
| astra-admin
| astra-console
vim /etc/pam.d/common-auth |
| auth required pam_listfile.so onerr=fail item=group sense=allow file=/etc/login.group.allow
